const CHESS_ALLOW_MANY_PIECES_ON_SQUARE = true;
const CHESS_ALLOW_NEW_PIECES = true;
const CHESS_MOVE_THROUGH_PIECES = true;
const CHESS_TIME_BETWEEN_MOVES = 2000;
const CHESS_DONT_LET_SINGLE_MOVE_MONOPOLIZE = true;
